export const WEEKLY_DATA = [
  {
    id: 0,
    day: "Monday",
    tempratue: "16",
    realFeel: "18",
    wind: "5-8",
    humidity: "51",
    sunrise: "6:02",
    sunset: "9:18",
    weather: "sunny",
  },
  {
    id: 1,
    day: "Tuesday",
    tempratue: "10",
    realFeel: "18",
    wind: "5-8",
    humidity: "51",
    sunrise: "6:02",
    sunset: "9:18",
    weather: "rainy",
  },
  {
    id: 2,
    day: "Wednesday",
    tempratue: "15",
    realFeel: "18",
    wind: "5-8",
    humidity: "51",
    sunrise: "6:02",
    sunset: "9:18",
    weather: "clouds",
  },
  {
    id: 3,
    day: "Thursday",
    tempratue: "11",
    realFeel: "18",
    wind: "5-8",
    humidity: "51",
    sunrise: "6:02",
    sunset: "9:18",
    weather: "clouds",
  },
  {
    id: 4,
    day: "Friday",
    tempratue: "18",
    realFeel: "18",
    wind: "5-8",
    humidity: "51",
    sunrise: "6:02",
    sunset: "9:18",
    weather: "haze",
  },
  {
    id: 5,
    day: "Saturday",
    tempratue: "12",
    realFeel: "18",
    wind: "5-8",
    humidity: "51",
    sunrise: "6:02",
    sunset: "9:18",
    weather: "sunny",
  },
  {
    id: 6,
    day: "Sunday",
    tempratue: "10",
    realFeel: "18",
    wind: "5-8",
    humidity: "51",
    sunrise: "6:02",
    sunset: "9:18",
    weather: "rainy",
  },
];
